# Generated by Django 2.2.4 on 2019-08-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('team', models.CharField(choices=[('COMM', 'COMMERCIAL'), ('USPS', 'PUBLIC SECTOR')], max_length=4)),
                ('region', models.CharField(max_length=50)),
                ('primary_strength', models.CharField(choices=[('ADV', 'ADVISOR'), ('CON', 'CONNECTOR'), ('CRE', 'CREATOR'), ('EQU', 'EQUALIZER'), ('INF', 'INFLUENCER'), ('PIO', 'PIONEER'), ('PRO', 'PROVIDER'), ('STI', 'STIMULATOR'), ('TEA', 'TEACHER')], max_length=3)),
                ('secondary_strength', models.CharField(choices=[('ADV', 'ADVISOR'), ('CON', 'CONNECTOR'), ('CRE', 'CREATOR'), ('EQU', 'EQUALIZER'), ('INF', 'INFLUENCER'), ('PIO', 'PIONEER'), ('PRO', 'PROVIDER'), ('STI', 'STIMULATOR'), ('TEA', 'TEACHER')], max_length=3)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
