# Generated by Django 2.2.4 on 2019-08-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190816_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cec',
            field=models.CharField(default='test', max_length=25),
            preserve_default=False,
        ),
    ]
