# Generated by Django 2.2.4 on 2019-08-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_tags', '0002_auto_20190819_1313'),
        ('profiles', '0004_auto_20190816_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(to='profile_tags.ProfileTag'),
        ),
    ]
