# Generated by Django 2.2.4 on 2019-09-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(choices=[('A', 'All'), ('C', 'Central'), ('E', 'East'), ('S', 'South'), ('W', 'West')], max_length=1),
        ),
    ]
