# Generated by Django 2.2.4 on 2019-10-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='geo',
            field=models.CharField(choices=[('USCAN', 'Americas'), ('EMEAR', 'EMEAR'), ('LATAM', 'LATAM'), ('APJC', 'APJC'), ('UNK', 'Unknown')], default='UNK', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='primary_strength',
            field=models.CharField(choices=[('ADV', 'Advisor'), ('CON', 'Connector'), ('CRE', 'Creator'), ('EQU', 'Equalizer'), ('INF', 'Influencer'), ('PIO', 'Pioneer'), ('PRO', 'Provider'), ('STI', 'Stimulator'), ('TEA', 'Teacher'), ('UNK', 'Unknown')], max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(choices=[('A', 'All'), ('C', 'Central'), ('E', 'East'), ('O', 'Other'), ('S', 'South'), ('W', 'West')], max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='secondary_strength',
            field=models.CharField(choices=[('ADV', 'Advisor'), ('CON', 'Connector'), ('CRE', 'Creator'), ('EQU', 'Equalizer'), ('INF', 'Influencer'), ('PIO', 'Pioneer'), ('PRO', 'Provider'), ('STI', 'Stimulator'), ('TEA', 'Teacher'), ('UNK', 'Unknown')], max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.CharField(choices=[('TEMP', 'TEMP'), ('COMM', 'Commercial'), ('USPS', 'Public Sector')], max_length=4),
        ),
    ]
