# Generated by Django 2.2.4 on 2019-10-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20191024_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='static/assets/blank.jpg', upload_to='static/assets/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='geo',
            field=models.CharField(choices=[('APJC', 'APJC'), ('EMEAR', 'EMEAR'), ('GLOBE', 'Global'), ('LATAM', 'LATAM'), ('TEMP', 'TEMP'), ('USCAN', 'Americas')], max_length=5),
        ),
    ]
