# Generated by Django 2.2.4 on 2019-09-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_tags', '0002_auto_20190819_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiletag',
            options={'ordering': ['text']},
        ),
        migrations.AddField(
            model_name='profiletag',
            name='tag_color',
            field=models.CharField(default='000000', max_length=6),
            preserve_default=False,
        ),
    ]
