# Generated by Django 2.2.4 on 2019-10-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factoids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoid',
            name='is_fun',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
